---
# yamllint disable rule:line-length
format: 1
ambertools:
  defaults:
    group: EM 
    overlay: base
    relstage: stable

  versions:
    26:
      variants:
        - overlay: Alps
          target_cpus: [x86_64]
          systems: [.*.merlin7.psi.ch]
          build_requires:
            - gcc/12.3.0
            - mpich/4.3.1
            - cuda/12.9.1
            - Python/3.10.16
          relstage: stable
          runtime_deps:
            - gcc/12.3.0
            - mpich/4.3.1
            - cuda/12.9.1
            - Python/3.10.16
        - overlay: Alps
          target_cpus: [aarch64]
          systems: [gpu0.*.merlin7.psi.ch]
          relstage: unstable
          build_requires:
            - gcc/12.3.0
            - mpich/4.3.1
            - cuda/12.9.1
            - Python/3.10.13
          runtime_deps:
            - gcc/12.3.0
            - mpich/4.3.1
            - cuda/12.9.1
            - Python/3.10.13
