---
# yamllint disable rule:line-length
format: 1
fpart:
  defaults:
    group: Tools
    overlay: base
    relstage: stable
    urls:                                               
      - url: https://github.com/martymac/$P/archive/refs/tags/$P-${V_PKG}.tar.gz

  shasums:                                              
    fpart-1.7.0.tar.gz: e5f82dd90001ed53200b2383bcfd520b1d8ee06d6a2a75b39d37d68daef20c88

  versions:
    1.7.0:
      variants:
        - overlay: base
          target_cpus: [x86_64]
          systems: [.*.merlin7.psi.ch]
          relstage: stable
        - overlay: base
          target_cpus: [aarch64]
          systems: [gpu0.*.merlin7.psi.ch]
          relstage: stable
